name: Release a new version

on: [workflow_dispatch]

permissions:
  actions: write     
  checks: write      
  pull-requests: write
  contents: read
  packages: write

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set safe git dir
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Tag repository
        id: tagRepo
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
